name: "Regression Testing using local provided PAT"
on:
  workflow_dispatch:

jobs:
  regression-local-pat:
    name: Regression Testing with local PAT
    runs-on: ubuntu-20.04
    steps:
      - name: Git Checkout
        uses: actions/checkout@v4
        with:
          path: ghas-metrics-report
      
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '14'

      - name: Install Dependencies
        run: npm install
        working-directory: ./ghas-metrics-report

      - name: Test Action
        uses: ./ghas-metrics-report
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
          RUN_USING_ACT: "true"
        with:
          repo: "helloworld"
          org: "DarkWarriorGo"
          features: "dependabot, code-scanning, secret-scanning"
          frequency: "daily"
          output-format: "json, pdf, issues"

      - name: Verify Report Generation
        run: |
          if [ ! -f ghas-metrics-report/dist/report.json ]; then
            echo "Report not generated!"
            exit 1
          fi
          
      - name: Upload GHAS metrics report
        uses: actions/upload-artifact@v4
        with:
          name: ghas-metrics-report
          path: ghas-metrics-report/dist/report.json
