name: delete branchs
on: workflow_dispatch
jobs:
  delete-branch:
    runs-on: ubuntu-latest
    steps:
      - name: checkout code
        uses: actions/checkout@v2
      - name: Cleanup Stale Branches
        uses: cbrgm/cleanup-stale-branches-action@v1
        with:
          token: ${{ secrets.TESTING_GITHUB_TOKEN }}
          repository: ${{ github.repository }}
          ignore-branches: "staging"
          last-commit-age-days: 365
          dry-run: true
