name: TruffleHog Scan

on:
  push:
    branches:
      - master
  pull_request:

jobs:
  trufflehog:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: TruffleHog Scan
        id: trufflehog
        uses: trufflesecurity/trufflehog@add-actions-cli-switch
        with:
          path: ./
          base: "${{ github.event.repository.default_branch }}"
          head: HEAD
          extra_args: --debug --only-verified

      - name: Fail if secrets detected
        run: |
          if [ "${{ steps.trufflehog.outputs.exit_code }}" -ne 0 ]; then
            echo "Secrets detected by TruffleHog."
            exit 1
          fi
